### ISSUE TITLE
 How to prevent "floatingChild" widget float outside the "child" widget

### ISSUE THREAD

**Issue by devsideal** [FMorschel/floating_overlay#7]
I need to float the `floatingChild` widget only inside the `child` widget, It's working fine for three edges Top, Left and Right but not for the Bottom (see the below video)

https://github.com/FMorschel/floating_overlay/assets/91250232/95c6ec58-5307-463d-bd92-f0407b74c8bc

Code is:
   ```
FloatingOverlayController _floatingController = FloatingOverlayController.relativeSize(
      maxScale: 2.0,
      minScale: 1.0,
      start: Offset.zero,
      padding: const EdgeInsets.all(20.0),
      constrained: true,
    );   
   
FloatingOverlay(
   controller: _floatingController,
   floatingChild: Container(height: 50, width: 50, color: Colors.red,),
   child: Container(height: 300, width: 500, color: Colors.green,) );
```

**How to restrict to don't go outside from the bottom as well?**

**Comment by FMorschel** [comment]
The controller has a parameter called `constrained`:

```dart
    /// If the floating child's space to float will be limited by the maximum
    /// size that the FloatingOverlay can be.
    bool constrained = false,
```

In this case, you are only constrained from the sides because the floating widget cannot go outside the screen and the padding is considered for the entire screen area.

**Comment by devsideal** [comment]
I want, the floating widget (red container) should not go to outside the child widget (green container) that's why i used 
`bool constrained = true`  But why it's allowing to go outside from the bottom side (see in the video)?

**Comment by FMorschel** [comment]
Sorry for the really long delay! You're doing it the wrong way around. The green `Container` should be the `FloatingOverlay` parent for it to constrain the size.

E.g.:

```dart
Container(
  height: 300, 
  width: 500, 
  color: Colors.green,
  child: FloatingOverlay(
    controller: _floatingController,
    floatingChild: Container(height: 50, width: 50, color: Colors.red,),
  ),
);
```
